# Generated by Django 4.2.23 on 2025-09-03 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="workerprofile",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_user_ty_92c6d9_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_profile_complete",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.AddField(
            model_name="user",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Worker availability status"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_pickups_count",
            field=models.IntegerField(
                default=0, help_text="Number of active pickups for worker"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rating_average",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("worker", "Worker"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="service_radius_km",
            field=models.IntegerField(
                default=5, help_text="Service radius in kilometers"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_user_role_36d76d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["latitude", "longitude"], name="users_user_latitud_ee15ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_available", "pending_pickups_count"],
                name="users_user_is_avai_f7a31c_idx",
            ),
        ),
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
        migrations.DeleteModel(
            name="WorkerProfile",
        ),
    ]
