/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as trashBeeTokenSol from "./TrashBeeToken.sol";
export { KlynaaToken__factory } from "./KlynaaToken__factory";
