/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as trashBeeTokenSol from "./TrashBeeToken.sol";
export type { trashBeeTokenSol };
export type { KlynaaToken } from "./KlynaaToken";
export * as factories from "./factories";
export { KlynaaToken__factory } from "./factories/KlynaaToken__factory";
