# Generated by Django 4.2.23 on 2025-09-03 14:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bins", "0002_pickuprequest_remove_bin_bins_bin_status_e3b5f1_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrowAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("locked", "Locked"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_accounts_as_payee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_accounts_as_payer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pickup_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow_account",
                        to="bins.pickuprequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="XAF", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit to Escrow"),
                            ("release", "Release from Escrow"),
                            ("refund", "Refund to Payer"),
                            ("fee", "Platform Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="XAF", max_length=3)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mtn_money", "MTN Mobile Money"),
                            ("orange_money", "Orange Money"),
                            ("stripe", "Stripe"),
                            ("cash", "Cash"),
                            ("wallet", "TrashBee Wallet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_data", models.JSONField(blank=True, default=dict)),
                (
                    "escrow_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.escrowaccount",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=200)),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.userwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="payments_wa_wallet__9a8a81_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="payments_wa_transac_b6f1b4_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("balance__gte", 0)), name="positive_balance"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["status"], name="payments_pa_status_b6726a_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider", "provider_transaction_id"],
                name="payments_pa_provide_a7d2ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["transaction_type"], name="payments_pa_transac_55c76b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowaccount",
            index=models.Index(fields=["status"], name="payments_es_status_b64aa5_idx"),
        ),
        migrations.AddIndex(
            model_name="escrowaccount",
            index=models.Index(
                fields=["payer", "status"], name="payments_es_payer_i_e75970_idx"
            ),
        ),
    ]
