# Generated by Django 4.2.23 on 2025-09-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("mtn_money", "MTN Mobile Money"),
                    ("orange_money", "Orange Money"),
                    ("stripe", "Stripe"),
                    ("cash", "Cash"),
                    ("wallet", "Klynaa Wallet"),
                ],
                max_length=20,
            ),
        ),
    ]
