# Generated by Django 4.2.7 on 2025-09-12 09:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_pickupproof_ai_verification_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_paymenttransaction_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base pickup fee', max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Performance bonus', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Final amount after fees', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('held', 'Held for Review'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('verification_required', models.BooleanField(default=False, help_text='Requires manual verification')),
                ('verification_notes', models.TextField(blank=True)),
                ('payout_method', models.CharField(choices=[('mtn_money', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('wallet', 'Klynaa Wallet')], default='mtn_money', max_length=20)),
                ('payout_reference', models.CharField(blank=True, max_length=100)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_earning', to='bins.pickuprequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['worker', 'status'], name='payments_wo_worker__521d28_idx'), models.Index(fields=['status', 'earned_at'], name='payments_wo_status_42a559_idx'), models.Index(fields=['worker', 'earned_at'], name='payments_wo_worker__e23b12_idx')],
            },
        ),
    ]
