# Generated by Django 4.2.23 on 2025-09-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bins", "0002_pickuprequest_remove_bin_bins_bin_status_e3b5f1_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("summary", models.JSONField(default=dict)),
                ("earnings_data", models.JSONField(default=dict)),
                ("pickups_data", models.JSONField(default=dict)),
                ("worker_performance_data", models.JSONField(default=dict)),
                ("generated_by", models.CharField(default="serverless", max_length=50)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EscrowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=20)),
                ("reason", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("processed_by", models.CharField(default="serverless", max_length=50)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "center_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("radius_km", models.DecimalField(decimal_places=2, max_digits=5)),
                ("workers_found", models.IntegerField(default=0)),
                ("workers_notified", models.IntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("processed_by", models.CharField(default="serverless", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.IntegerField(blank=True, null=True)),
                ("user_ids", models.JSONField(default=list)),
                ("notification_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("success", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("sent_by", models.CharField(default="serverless", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("data", models.JSONField(default=dict)),
                ("trends", models.JSONField(default=dict)),
                ("insights", models.JSONField(default=list)),
                ("top_performers", models.JSONField(default=list)),
                ("generated_by", models.CharField(default="serverless", max_length=50)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-week_start"],
                "indexes": [
                    models.Index(
                        fields=["week_start", "week_end"],
                        name="bins_weekly_week_st_311309_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="bins_weekly_created_34bd01_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklyanalytics",
            constraint=models.UniqueConstraint(
                fields=("week_start", "week_end"), name="unique_weekly_analytics"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="pickup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bins.pickuprequest",
            ),
        ),
        migrations.AddField(
            model_name="geolog",
            name="pickup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bins.pickuprequest",
            ),
        ),
        migrations.AddField(
            model_name="escrowlog",
            name="pickup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bins.pickuprequest",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyreport",
            index=models.Index(fields=["date"], name="bins_dailyr_date_2151db_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyreport",
            index=models.Index(
                fields=["created_at"], name="bins_dailyr_created_839101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["notification_type"], name="bins_notifi_notific_da8bd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["created_at"], name="bins_notifi_created_dcd476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["success"], name="bins_notifi_success_acb67a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geolog",
            index=models.Index(
                fields=["created_at"], name="bins_geolog_created_4c2017_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geolog",
            index=models.Index(
                fields=["center_latitude", "center_longitude"],
                name="bins_geolog_center__9d3c91_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="escrowlog",
            index=models.Index(fields=["action"], name="bins_escrow_action_585bd1_idx"),
        ),
        migrations.AddIndex(
            model_name="escrowlog",
            index=models.Index(
                fields=["created_at"], name="bins_escrow_created_a37ec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escrowlog",
            index=models.Index(
                fields=["payment_id"], name="bins_escrow_payment_48bb70_idx"
            ),
        ),
    ]
