# Generated by Django 4.2.24 on 2025-09-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0006_add_location_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bin',
            name='bins_bin_location_idx',
        ),
    ]
