# Generated by Django 4.2.23 on 2025-09-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bin_id",
                    models.CharField(
                        help_text="Physical bin identifier", max_length=20, unique=True
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.TextField(help_text="Human-readable address")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("partial", "Partially Full"),
                            ("full", "Full"),
                            ("overflowing", "Overflowing"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
                (
                    "fill_level",
                    models.IntegerField(default=0, help_text="Fill percentage 0-100"),
                ),
                (
                    "capacity_liters",
                    models.IntegerField(
                        default=120, help_text="Bin capacity in liters"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_pickup", models.DateTimeField(blank=True, null=True)),
                (
                    "battery_level",
                    models.IntegerField(
                        default=100, help_text="Sensor battery percentage"
                    ),
                ),
                ("is_online", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "fill_level"],
                        name="bins_bin_status_e3b5f1_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="bins_bin_latitud_3cd82b_idx",
                    ),
                ],
            },
        ),
    ]
