# Generated by Django 4.2.23 on 2025-09-03 14:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("disputed", "Disputed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=10
                    ),
                ),
                (
                    "actual_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                        ],
                        default="mobile_money",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("escrowed", "Escrowed"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("disputed", "Disputed"),
                            ("pending_cash", "Pending Cash Collection"),
                            ("collected_cash", "Cash Collected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Special instructions"),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="bin",
            name="bins_bin_status_e3b5f1_idx",
        ),
        migrations.RemoveField(
            model_name="bin",
            name="battery_level",
        ),
        migrations.RemoveField(
            model_name="bin",
            name="is_online",
        ),
        migrations.AddField(
            model_name="bin",
            name="label",
            field=models.CharField(
                default="Smart Bin", help_text="User-friendly name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="bin",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bin",
            name="address",
            field=models.TextField(
                default="Address not set", help_text="Human-readable address"
            ),
        ),
        migrations.AlterField(
            model_name="bin",
            name="capacity_liters",
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name="bin",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.000000"), max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="bin",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.000000"), max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="bin",
            name="status",
            field=models.CharField(
                choices=[
                    ("empty", "Empty"),
                    ("partial", "Partially Full"),
                    ("full", "Full"),
                    ("pending", "Pickup Pending"),
                ],
                default="empty",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(fields=["status"], name="bins_bin_status_cfaa9c_idx"),
        ),
        migrations.AddIndex(
            model_name="bin",
            index=models.Index(
                fields=["owner", "status"], name="bins_bin_owner_i_1d9d39_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bin",
            constraint=models.CheckConstraint(
                check=models.Q(("fill_level__gte", 0), ("fill_level__lte", 100)),
                name="fill_level_range",
            ),
        ),
        migrations.AddField(
            model_name="pickuprequest",
            name="bin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup_requests",
                to="bins.bin",
            ),
        ),
        migrations.AddField(
            model_name="pickuprequest",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup_requests_as_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pickuprequest",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup_requests_as_worker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pickuprequest",
            index=models.Index(fields=["status"], name="bins_pickup_status_f3b904_idx"),
        ),
        migrations.AddIndex(
            model_name="pickuprequest",
            index=models.Index(
                fields=["worker", "status"], name="bins_pickup_worker__1c4700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickuprequest",
            index=models.Index(
                fields=["owner", "status"], name="bins_pickup_owner_i_4a3b0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickuprequest",
            index=models.Index(
                fields=["payment_status"], name="bins_pickup_payment_9bf2d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pickuprequest",
            index=models.Index(
                fields=["created_at"], name="bins_pickup_created_e34f8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pickuprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["open", "accepted", "in_progress"])),
                fields=("bin",),
                name="unique_active_pickup_per_bin",
            ),
        ),
    ]
