# Generated by Django 4.2.7 on 2025-09-11 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bins', '0003_dailyreport_escrowlog_geolog_notificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='bin',
            name='qr_code_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique QR code identifier', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PickupProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('image', models.ImageField(upload_to='pickup_proofs/%Y/%m/%d/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_proofs', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='bins.pickuprequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='bins_pickup_status_c12c05_idx'), models.Index(fields=['type'], name='bins_pickup_type_1bc98c_idx'), models.Index(fields=['pickup', 'status'], name='bins_pickup_pickup__1da23f_idx')],
            },
        ),
    ]
